Feture: tela dados do usuário
paketaacademy/class2 pull request #103
Opened 2021-08-03 19:02 UTC by jesus91fael

2021-08-03 19:07 UTC, carolinespezzatto approved these changes

2021-08-03 19:12 UTC, lucasbarbosadias requested changes

2021-08-03 19:12 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/App/src/components/Body/index.jsx
> +
Pode apagar a linha 3 pois está vazia

2021-08-03 19:13 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Body/index.jsx
> +
ok, apaguei a linha

2021-08-03 19:14 UTC, lucasbarbosadias approved these changes

2021-08-03 19:15 UTC, mattheuzz approved these changes

2021-08-04 16:56 UTC, Tautorn requested changes

2021-08-04 16:56 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostCardFull.jsx
> +import {CardDiv, CardMediaDiv, StyledAvatar, TypographyDiv} from './Style.js'
Que tal `styles.js`?
Adicionar espaço após e antes das chaves { CardDIv.... TypographyDiv }`

E não deve ser utilziado nome de tags no nome dos estilos.

Card, Typography somente.

2021-08-04 16:56 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostCardFull.jsx
> +const PostCardFull = ({ body, display_name, profile_image, social_score, retweets, likes }) => {
O que é um Post Card Full?

2021-08-04 16:56 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostsFull.jsx
> +      `http://localhost:3000/feeds`,
fazer chamada por uma variável de ambiente.
Se mudar amanhã a porta como fica?

2021-08-04 17:23 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostCardFull.jsx
> +import {CardDiv, CardMediaDiv, StyledAvatar, TypographyDiv} from './Style.js'
ok, corrigido

2021-08-04 17:23 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostsFull.jsx
> +      `http://localhost:3000/feeds`,
ok, resolvido

2021-08-04 17:24 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostCardFull.jsx
> +const PostCardFull = ({ body, display_name, profile_image, social_score, retweets, likes }) => {
no caso, existe duas visualizações dos card, uma que é um box simples, e outra que possui um box com imagem, assim coloquei com nome de PostCardFull a visualização que possui imagem.

2021-08-04 17:26 UTC, mattheuzz approved these changes

2021-08-04 22:51 UTC, Tautorn requested changes

2021-08-04 22:51 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/Home/index.jsx
> +      <CreditoDetails/>
Não usar palavra em Português

2021-08-04 22:51 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/Home/index.jsx
> +    <HomeContainer>
Home

2021-08-05 13:41 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/pages/Home/index.jsx
> +      <CreditoDetails/>
Alterado

2021-08-05 13:42 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/pages/Home/index.jsx
> +    <HomeContainer>
não entendi, o que seria aqui?

2021-08-05 13:53 UTC, merged