feature: Influencers
paketaacademy/class2 pull request #104
Opened 2021-08-04 01:33 UTC by mattheuzz

Criação da pagina Influencers, alguns ajustes nas pastas

2021-08-04 14:00 UTC, jesus91fael approved these changes

2021-08-04 14:47 UTC, carolinespezzatto approved these changes

2021-08-04 21:25 UTC, talesperes requested changes

2021-08-04 21:25 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +      {console.log('teste', list.length)}
Poderia remover esses `console.log` ?

2021-08-04 21:25 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +        console.log(data)
Poderia remover esse `console.log` ?

2021-08-04 21:25 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +      `http://localhost:3000/influencers`,
Poderia fazer essa chamada por uma variável de ambiente?

2021-08-04 21:25 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/InfluencersPosts.jsx
> +export default function RecipeReviewCard({banner_image, profile_image, rank, twitter_screen_name, display_name}) {
Poderia adicionar espaço no começo e no final das chaves?
```suggestion
export default function RecipeReviewCard({ banner_image, profile_image, rank, twitter_screen_name, display_name }) {
```

2021-08-04 21:25 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/api.js
> +    baseURL: 'http://localhost:3000'
Poderia substituir por uma variável de ambiente?

2021-08-04 22:51 UTC, Tautorn requested changes

2021-08-04 22:51 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/InfluencersPosts.jsx
> +            <CardHeader
Corrigir identação de todos arquivos. Utilizar espaço 2

2021-08-04 22:51 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +                key={conteudo.identifier}
Não usar palavras em portugues.

2021-08-04 22:51 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +        list.length > 0 && list.map((conteudo) => {
Criar uma função para "resolver" o map, não é uma boa prática retornar com um conteúdo diretamente.

2021-08-05 12:57 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +      {console.log('teste', list.length)}
Removido

2021-08-05 13:28 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +        list.length > 0 && list.map((conteudo) => {
Criado uma função para o map

2021-08-05 13:28 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +                key={conteudo.identifier}
Troquei para Content

2021-08-05 13:28 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/InfluencersPosts.jsx
> +            <CardHeader
Corrigido o espaçamento

2021-08-05 13:29 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/api.js
> +    baseURL: 'http://localhost:3000'
Trocado para a variavel de ambiente

2021-08-05 13:29 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/InfluencersPosts.jsx
> +export default function RecipeReviewCard({banner_image, profile_image, rank, twitter_screen_name, display_name}) {
adicionado o espaço

2021-08-05 13:29 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +      `http://localhost:3000/influencers`,
troca feita

2021-08-05 13:29 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +      {console.log('teste', list.length)}
removido o console.log

2021-08-05 13:29 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Influencers/influencersCards.jsx
> +        console.log(data)
removido o console.log

2021-08-05 14:42 UTC, Tautorn approved these changes

2021-08-05 14:42 UTC, Tautorn commented
AProvado mas é preciso remover os ponto e vírgulas no sistema e não é preciso utilizar o useStyles.

2021-08-05 14:42 UTC, merged