Markets
paketaacademy/class2 pull request #105
Opened 2021-08-04 12:59 UTC by jesus91fael

Chore: alteração de estilização da tabela de criptomoedas

2021-08-04 16:14 UTC, mattheuzz approved these changes

2021-08-04 16:35 UTC, carolinespezzatto approved these changes

2021-08-04 21:21 UTC, talesperes requested changes

2021-08-04 21:21 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostCard.jsx
>  const PostCard = ({body, social_score, retweets, likes}) => {
Poderia colocar espaço no começo e no final das chaves? 
```suggestion
const PostCard = ({ body, social_score, retweets, likes }) => {
```

2021-08-04 21:21 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostCardFull.jsx
> +import {CardDiv, CardMediaDiv, StyledAvatar, TypographyDiv} from './Style.js'
Poderia colocar espaço no começo e no final das chaves?
```suggestion
import { CardDiv, CardMediaDiv, StyledAvatar, TypographyDiv } from './Style.js'
```

2021-08-04 21:21 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/components/Home/BtcDetails.jsx
> +import CompareArrowsIcon from '@material-ui/icons/CompareArrows';
Poderia remove o `;` ?

2021-08-04 21:21 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/components/InserirCredito/Inserir.jsx
> +import Button from '@material-ui/core/Button';
Poderia remover o `;` ?

2021-08-04 21:21 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/components/InserirCredito/Inserir.jsx
> +  const classes = useStyles();
Poderia remover o `;` ?

2021-08-04 21:21 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/components/InserirCredito/Style.js
> +import Button from '@material-ui/core/Button';
Poderia remover o `;` ?

2021-08-04 21:21 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
>  import TableMarket from '../components/TableMarket';
Poderia remover os `;` ?

2021-08-04 22:50 UTC, Tautorn requested changes

2021-08-04 22:50 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/index.js
> +app.listen(3000)
.env

2021-08-04 22:50 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Feeds/style.js
> +    padding-top: 56.25%;
por que padding "quebrado"? E não deve ser feito em percentual.

2021-08-04 22:50 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Home/BtcDetails.jsx
> +      <div>0,09 BTC</div>
Por que está fixo?

2021-08-04 22:50 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Home/BtcDetails.jsx
> +function BtcDetails() {
Btc igual Bitcoin? Se for mudar o nome.

2021-08-04 22:50 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/InserirCredito/Inserir.jsx
> +    '& > *': {
O que é isso?

2021-08-05 13:45 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostCard.jsx
>  const PostCard = ({body, social_score, retweets, likes}) => {
alterado

2021-08-05 13:46 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Feeds/PostCardFull.jsx
> +import {CardDiv, CardMediaDiv, StyledAvatar, TypographyDiv} from './Style.js'
alterado

2021-08-05 13:46 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Home/BtcDetails.jsx
> +import CompareArrowsIcon from '@material-ui/icons/CompareArrows';
removido

2021-08-05 13:46 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/InserirCredito/Inserir.jsx
> +import Button from '@material-ui/core/Button';
removido

2021-08-05 13:47 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/InserirCredito/Inserir.jsx
> +  const classes = useStyles();
removido

2021-08-05 13:47 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/InserirCredito/Style.js
> +import Button from '@material-ui/core/Button';
removido

2021-08-05 13:47 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
>  import TableMarket from '../components/TableMarket';
removido

2021-08-05 13:48 UTC, jesus91fael commented on projects/crypto-currency/destemidos/Api/index.js
> +app.listen(3000)
alterado

2021-08-05 13:50 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Feeds/style.js
> +    padding-top: 56.25%;
é porque tinha vindo do material UI, mas alterei aqui

2021-08-05 13:50 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Home/BtcDetails.jsx
> +      <div>0,09 BTC</div>
porque foi feito so layout, até o momento

2021-08-05 13:52 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Home/BtcDetails.jsx
> +function BtcDetails() {
alterado

2021-08-05 13:59 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/InserirCredito/Inserir.jsx
> +    '& > *': {
era d material UI, resolvido

2021-08-05 14:45 UTC, talesperes approved these changes

2021-08-05 14:45 UTC, talesperes commented
Conflitos

2021-08-06 12:03 UTC, merged