Hero Destemidos e Market
paketaacademy/class2 pull request #106
Opened 2021-08-04 14:06 UTC by carolinespezzatto

Criando Hero na tela Destemidos e Market que será apresentado somente quando o usuário não estiver logado. Incluído também uma opção de checkout no menu lateral

2021-08-04 16:11 UTC, jesus91fael approved these changes

2021-08-04 16:15 UTC, mattheuzz approved these changes

2021-08-04 21:15 UTC, talesperes requested changes

2021-08-04 21:15 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/.env
> +REACT_APP_API_URL=http://localhost:3000/
Está correto esse arquivo `.env` dentro da pasta `src`? Ele não deveria ficar na raiz do projeto?

2021-08-04 21:15 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Destemidos/components/TransitionsPopper/index.js
> +import { PaperDiv } from '../../style';
Poderia remover os `;` ?

2021-08-04 21:15 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Destemidos/components/TransitionsPopper/index.js
> +  const id = open ? 'transitions-popper' : undefined;
Poderia remover os `;` ?

2021-08-04 21:15 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/SignOut/index.js
> +import PopupState, { bindTrigger, bindMenu } from 'material-ui-popup-state';
Poderia remover os `;` ?

2021-08-04 22:48 UTC, Tautorn requested changes

2021-08-04 22:48 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignOut/index.js
> +          <Button className='button--config' variant="contained" {...bindTrigger(popupState)}>
O que são `binds`?

2021-08-05 12:40 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/App/src/.env
> +REACT_APP_API_URL=http://localhost:3000/
Não estava correto, foi sem querer. Realoquei o arquivo para a raiz do App.

2021-08-05 12:40 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/App/src/pages/Destemidos/components/TransitionsPopper/index.js
> +import { PaperDiv } from '../../style';
Removido!

2021-08-05 12:40 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/App/src/pages/Destemidos/components/TransitionsPopper/index.js
> +  const id = open ? 'transitions-popper' : undefined;
Removido!

2021-08-05 12:40 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/App/src/pages/SignOut/index.js
> +import PopupState, { bindTrigger, bindMenu } from 'material-ui-popup-state';
Removido!

2021-08-05 13:49 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/App/src/pages/SignOut/index.js
> +          <Button className='button--config' variant="contained" {...bindTrigger(popupState)}>
Esse botão de SignOut foi alterado após envio desse PR pois não estava legal dessa forma. Alteração commitada.

2021-08-05 13:55 UTC, talesperes requested changes

2021-08-05 13:55 UTC, talesperes commented on projects/crypto-currency/destemidos/Api/.env
> +MONGODB=mongodb+srv://academy:paketaacademy@cluster0.4zf3i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
O arquivo `.env` não deve ser enviado para o github, adicionar ao `.gitignore`

2021-08-05 14:10 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/Api/.env
> +MONGODB=mongodb+srv://academy:paketaacademy@cluster0.4zf3i.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
deletado!

2021-08-05 14:11 UTC, talesperes approved these changes

2021-08-06 11:49 UTC, merged