Feture:
paketaacademy/class2 pull request #108
Opened 2021-08-04 18:10 UTC by alissonperim

Cria algumas rotas no arquivo App.js, foram criados os componentes TemplateMain e TemplateAuth que ficaram responsáveis por renderizar os componentes devidamente em seus templates e também foi criado o componente Feed responsável por manipular  e retornar os feeds que da API.

2021-08-04 21:33 UTC, talesperes requested changes

2021-08-04 21:33 UTC, talesperes commented on projects/crypto-currency/iluminados/api/src/routes/modules/register.js
> +  const password = req.body.password
Oque acha de fazer assim?
```suggestion
  const { email, password } = req.body
```

2021-08-04 21:33 UTC, talesperes commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/data-base.js
>  mongoose.connect(MONGO_URI, params);
Poderia remover o `;` ?

2021-08-04 21:33 UTC, talesperes commented on projects/crypto-currency/iluminados/app/src/components/Feed/HandleWithFeed.jsx
> +      {console.log(list)}
Poderia remover esse `console.log` ?

2021-08-04 21:33 UTC, talesperes commented on projects/crypto-currency/iluminados/app/src/components/Feed/HandleWithFeed.jsx
> +  const url = "http://localhost:3030/feeds"
Poderia substituir por uma variável de ambiente?

2021-08-04 21:33 UTC, talesperes commented on projects/crypto-currency/iluminados/app/src/components/Login/index.jsx
> +import { Link } from "react-router-dom";
Poderia remover esses `;` ?

2021-08-04 21:33 UTC, talesperes commented on projects/crypto-currency/iluminados/app/src/components/Navbar/index.jsx
> +  const anchorRef = React.useRef(null);
Poderia remover esses `;` ?

2021-08-04 21:33 UTC, talesperes commented on projects/crypto-currency/iluminados/app/src/components/Navbar/index.jsx
> +  const prevOpen = React.useRef(open);
Poderia remoer esse `;` ?

2021-08-04 22:48 UTC, Tautorn requested changes

2021-08-04 22:48 UTC, Tautorn commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/lunar-crush-api.js
> +    url: `https://api.lunarcrush.com/v2?data=${route}&key=l1k21q9bpmccoswx1ni3ao&limit=${limit}&page=${page}`,
Por que foi alterado a chave?

2021-08-04 22:48 UTC, Tautorn commented on projects/crypto-currency/iluminados/api/src/server.js
> +app.listen(3030, () => {
Adicionar .env

2021-08-04 22:48 UTC, Tautorn commented on projects/crypto-currency/iluminados/app/src/components/Register/index.jsx
> +          <Link to="/logar"><Btn color="inherit">Cancelar</Btn></Link>
Evitar nomes "comprimidos".
`Mudar de Btn para Button`. É necessário ser o mais explícito possível com a criação de cada nome.

2021-08-04 22:48 UTC, Tautorn commented on projects/crypto-currency/iluminados/app/src/components/TemplateMain/styles.js
> +export const ContentContainer = styled.div`
Ou é Content ou é Container.
Container pode possuir um content mas não pode ser os dois.

2021-08-05 01:03 UTC, alissonperim commented on projects/crypto-currency/iluminados/app/src/components/Login/index.jsx
> +import { Link } from "react-router-dom";
Vou remover todos

2021-08-05 01:03 UTC, alissonperim commented on projects/crypto-currency/iluminados/app/src/components/Navbar/index.jsx
> +  const anchorRef = React.useRef(null);
Vou remover todos

2021-08-05 01:03 UTC, alissonperim commented on projects/crypto-currency/iluminados/app/src/components/Navbar/index.jsx
> +  const prevOpen = React.useRef(open);
Vou remover todos

2021-08-05 01:03 UTC, alissonperim commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/lunar-crush-api.js
> +    url: `https://api.lunarcrush.com/v2?data=${route}&key=l1k21q9bpmccoswx1ni3ao&limit=${limit}&page=${page}`,
Eu tinha imaginado que era necessário adicionar a minha chave para fazer as requisições, por isso alterei

2021-08-05 01:05 UTC, alissonperim commented on projects/crypto-currency/iluminados/app/src/components/TemplateMain/styles.js
> +export const ContentContainer = styled.div`
Eu havia imaginado que seria tido como: Container do conteúdo mas vou modificar, obrigado pela informação

2021-08-05 01:29 UTC, alissonperim commented on projects/crypto-currency/iluminados/api/src/routes/modules/register.js
> +  const password = req.body.password
Top! Vou alterar

2021-08-05 01:30 UTC, alissonperim commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/data-base.js
>  mongoose.connect(MONGO_URI, params);
Feito!

2021-08-05 01:34 UTC, alissonperim commented on projects/crypto-currency/iluminados/app/src/components/Feed/HandleWithFeed.jsx
> +  const url = "http://localhost:3030/feeds"
Tentei fazer a modificação, porém eu construo um componente com os valores desse hook e não foi possível modificar para uma variável de ambiente

2021-08-05 01:36 UTC, alissonperim commented on projects/crypto-currency/iluminados/app/src/components/Register/index.jsx
> +          <Link to="/logar"><Btn color="inherit">Cancelar</Btn></Link>
Alterado!

2021-08-05 01:37 UTC, alissonperim commented on projects/crypto-currency/iluminados/app/src/components/TemplateMain/styles.js
> +export const ContentContainer = styled.div`
Alterado para Content

2021-08-05 01:40 UTC, alissonperim commented on projects/crypto-currency/iluminados/app/src/components/Feed/HandleWithFeed.jsx
> +      {console.log(list)}
Feito!

2021-08-05 11:25 UTC, renatosheep approved these changes
ok.

2021-08-05 13:41 UTC, talesperes requested changes

2021-08-05 13:41 UTC, talesperes commented on projects/crypto-currency/iluminados/app/src/components/Feed/HandleWithFeed.jsx
> +  const url = "http://localhost:3030/feeds"
Porque não foi possível? Acontece algum erro?

2021-08-06 11:49 UTC, merged