Chore: registration validation
paketaacademy/class2 pull request #109
Opened 2021-08-04 18:24 UTC by lucasbarbosadias

Faço uma verificação no back-end e caso o e-mail já esteja cadastrado ele retorna um erro para o front-end, caso não esteja cadastrado ainda ele realiza o cadastro no banco.

2021-08-04 18:28 UTC, mattheuzz approved these changes

2021-08-04 21:01 UTC, talesperes requested changes

2021-08-04 21:01 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +  const [teste, setTeste] = useState(true)
Aqui deveria ser `teste` mesmo?

2021-08-04 21:01 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +      console.log(response.data)
Poderia remover esse `console.log` ?

2021-08-04 22:46 UTC, Tautorn requested changes

2021-08-04 22:46 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/index.js
> +app.listen(3000)
adicionar .env

2021-08-04 22:46 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/routes/singup.js
> +    } else {
evitar if e else.
Se o e-mail já está cadastrado então já pode fazer o return.

2021-08-04 22:46 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/routes/singup.js
> +        res.status(201).send('Cadastrado realizado com sucesso!')
```suggestion
        res.status(201).send('Cadastro realizado com sucesso!')
```

2021-08-04 22:46 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +    inputs.password !== inputs.confirmPassword || inputs.password === '' ? setTeste(true) : setTeste(false)
Essa validação deve ser realizada em uma função separada.

2021-08-04 23:11 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +  const [teste, setTeste] = useState(true)
Como eu tinha feito essa branch a partir de uma que estava aberta os commits anteriores vieram junto nesse PR, ai eu alterei isso no PR anterior mais aqui não alterou, ai eu dei um pull nessa branch com a main e já mudou o nome de teste para o correto.

2021-08-05 00:37 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/Api/routes/singup.js
> +    } else {
Estou pensando como validar se o e-mail existe para retornar uma coisa e caso não exista retorne outra, não sei se estou "encaixotado" no modo de pensar, mas se eu fizer um ternário chamando uma função que faça o cadastro daria certo? Fica um pouco mais organizado mas não sei se ainda seria o melhor modo de se fazer por exemplo assim:
`const createUser = () => {
  const user = new Users({ email, password })
  await user.save()
  res.status(201).send('Cadastro realizado com sucesso!')
}

try {
  const foundUser = await Users.findOne({ email: email }).exec()
  foundUser ? res.status(409).send('E-mail já cadastrado!') : createUser()
} catch (err) {
  res.send(err)
}`

2021-08-05 00:55 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/Api/routes/singup.js
> +    } else {
O Tales me ajudou agora consegui entender o que quis dizer, vou subir as alterações!

2021-08-05 13:16 UTC, talesperes approved these changes

2021-08-05 13:20 UTC, merged