Chore: login
paketaacademy/class2 pull request #110
Opened 2021-08-04 18:27 UTC by mattheuzz

Fazendo a integração do Login do back, front e banco de dados

2021-08-04 19:02 UTC, carolinespezzatto approved these changes

2021-08-04 21:07 UTC, talesperes requested changes

2021-08-04 21:07 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +//import api from '../api';
Poderia remover esse comentário?

2021-08-04 21:07 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/SignIn/index.js
> +    return <MuiAlert elevation={6} variant="filled" {...props} />;
Poderia remove o `;` ?
```suggestion
    return <MuiAlert elevation={6} variant="filled" {...props} />
```

2021-08-04 21:07 UTC, talesperes commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +
Poderia remover essa linha vazia?

```suggestion
      if(foundUser) {
        res.status(200).send('Login realizado com sucesso')
```

2021-08-04 21:07 UTC, talesperes commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +  const password = req.body.password
Oque acha de fazer assim?
```suggestion
  const { email, password } = req.body
```

2021-08-04 22:44 UTC, Tautorn requested changes

2021-08-04 22:44 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/index.js
> +app.listen(3000)
adicionar a porta por .env

2021-08-04 22:44 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +                const { data } = await response.json()
não precisa desse await

2021-08-04 22:44 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +            .then(async response => {
não precisa do async.

2021-08-05 12:53 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +            .then(async response => {
Bruno eu tententei remover o async  e o await, mas ai a pagina não carrega, dá erro e não renderiza a tabela

2021-08-05 12:54 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +                const { data } = await response.json()
Bruno eu tententei remover o async  e o await, mas ai a pagina não carrega, dá erro e não renderiza a tabela

2021-08-05 12:54 UTC, mattheuzz commented on projects/crypto-currency/destemidos/Api/index.js
> +app.listen(3000)
Trocada a porta por um .env

2021-08-05 12:54 UTC, mattheuzz commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +  const password = req.body.password
Feito a desestruturação

2021-08-05 12:55 UTC, mattheuzz commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +
removido a linha

2021-08-05 12:55 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/SignIn/index.js
> +    return <MuiAlert elevation={6} variant="filled" {...props} />;
removido os dois pontos

2021-08-05 12:55 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +//import api from '../api';
removido o comentario

2021-08-05 14:20 UTC, jesus91fael approved these changes

2021-08-05 16:59 UTC, talesperes approved these changes

2021-08-06 12:03 UTC, merged