Feature jwt
paketaacademy/class2 pull request #113
Opened 2021-08-05 14:20 UTC by mattheuzz

Fiz com que o JWT gerasse o Token, ajustei a validação do login e criptografei a senha

2021-08-05 14:21 UTC, jesus91fael approved these changes

2021-08-05 14:49 UTC, talesperes requested changes

2021-08-05 14:49 UTC, talesperes commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +//import api from '../api';
Remover comentario

2021-08-05 14:49 UTC, talesperes commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +  const Users = await userModel.findOne({ email })
o findOne só vai retornar apenas 1 user, oque acha de fazer essa alteração?
```suggestion
  const user = await userModel.findOne({ email })
```

2021-08-05 16:56 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +//import api from '../api';
Pagado o comentario

2021-08-05 16:56 UTC, mattheuzz commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +  const Users = await userModel.findOne({ email })
feito a substituição

2021-08-06 12:04 UTC, Tautorn commented
conflitos

2021-08-06 12:10 UTC, mattheuzz commented
> 
> 
> conflitos

Resolvido o conflito

2021-08-06 13:39 UTC, carolinespezzatto approved these changes

2021-08-06 15:10 UTC, merged