Coin to day
paketaacademy/class2 pull request #125
Opened 2021-08-06 18:16 UTC by Leringit

criado retorno da moeda diária e sua estilização.

2021-08-10 12:24 UTC, Tautorn requested changes

2021-08-10 12:24 UTC, Tautorn commented on projects/crypto-currency/iluminados/app/src/components/Coinoftheday/index.jsx
> +      `${API}coinoftheday`,
É preciso ajustar no BE, nome de api deve ser separado por hífen

`coin-of-the-day`

2021-08-10 12:24 UTC, Tautorn commented on projects/crypto-currency/iluminados/app/src/components/Coinoftheday/index.jsx
> +      {day()}
`Day` é muito vago, quando se renderiza algo (cria algum conteúdo) utlizamos o nome `render` como pré-fixo.
Exemplo: `renderCoins`.

2021-08-10 12:24 UTC, Tautorn commented on projects/crypto-currency/iluminados/app/src/components/Coinoftheday/index.jsx
> +        console.log(coin)
remover console

2021-08-11 12:10 UTC, Tautorn approved these changes

2021-08-11 16:19 UTC, renatosheep approved these changes

2021-08-11 17:37 UTC, merged