Footer destemidos
paketaacademy/class2 pull request #127
Opened 2021-08-06 18:33 UTC by cogumos

2021-08-06 18:34 UTC, carolinespezzatto approved these changes

2021-08-06 18:39 UTC, mattheuzz approved these changes

2021-08-09 12:48 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +                    <FontAwesomeIcon icon={[faDiscord]} fixedWidth /> */}
Isso era para estar comentado mesmo?

2021-08-09 12:48 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +                    <FontAwesomeIcon icon={[faDiscord]} fixedWidth /> */}
Isso era pra estar comentado mesmo? 2

2021-08-09 12:49 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +                <UlWrap>
usar outro nome, sem estar diretamente ligado a tag (exemplo sem usar a 'ul')

2021-08-09 12:50 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +                    <div class="right">
className no lugar de class

2021-08-09 12:51 UTC, jesus91fael requested changes

2021-08-09 12:51 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +render(<index />, document.getElementById("root"));
tirar o ';'

2021-08-09 13:35 UTC, carolinespezzatto requested changes

2021-08-09 13:35 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/App/src/components/Footer/style.js
> +import styled from "styled-components";
remover ";"

2021-08-09 13:35 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +
remover linhas vazias, manter somente uma

2021-08-09 13:35 UTC, carolinespezzatto commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +
remover linhas vazias, manter somente uma

2021-08-09 18:23 UTC, mattheuzz commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
>  import TableMarket from '../components/TableMarket';
Remover o ";"

2021-08-10 12:09 UTC, Tautorn requested changes

2021-08-10 12:09 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +// import { faTwitter, faTelegramPlane, faRedditAlien, faLinkedinIn, faFacebookF, faInstagram, faDiscord } from "@fortawesome/free-solid-svg-icons"
remover comentários

2021-08-11 22:08 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +// import { faTwitter, faTelegramPlane, faRedditAlien, faLinkedinIn, faFacebookF, faInstagram, faDiscord } from "@fortawesome/free-solid-svg-icons"
Removido!

2021-08-11 22:10 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
>  import TableMarket from '../components/TableMarket';
Removi!

2021-08-11 22:11 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +
Removi.

2021-08-11 22:12 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +
Removido.

2021-08-11 22:17 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/style.js
> +import styled from "styled-components";
Removido.

2021-08-11 22:18 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +render(<index />, document.getElementById("root"));
Removido.

2021-08-11 22:20 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +                    <div class="right">
Ajeitei.

2021-08-11 22:22 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +                <UlWrap>
Alterado.

2021-08-11 22:31 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +                    <FontAwesomeIcon icon={[faDiscord]} fixedWidth /> */}
Não, eu botei pra mas retirei porque não utilizei mais.

2021-08-11 22:31 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Footer/index.jsx
> +                    <FontAwesomeIcon icon={[faDiscord]} fixedWidth /> */}
Não, eu botei pra mas retirei porque não utilizei mais.

2021-08-12 00:19 UTC, talesperes commented
conflitos

2021-08-12 12:21 UTC, lucasbarbosadias approved these changes

2021-08-12 15:30 UTC, jesus91fael approved these changes

2021-08-12 17:00 UTC, lucasbarbosadias approved these changes

2021-08-13 11:57 UTC, carolinespezzatto approved these changes

2021-08-13 19:06 UTC, closed without merging