chore: melhoria na cisualizção da compra de criptomoeda
paketaacademy/class2 pull request #139
Opened 2021-08-10 19:01 UTC by jesus91fael

2021-08-10 20:05 UTC, lucasbarbosadias requested changes

2021-08-10 20:05 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/TableBody/index.jsx
> +                        </TableRow>
Revisar espaçamentos com tab-size que estão com 4, e mudar para 2

2021-08-10 20:05 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +import TableMarket from '../components/TableMarket';
Remover ";"

2021-08-10 20:05 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +      setloading(true);
Remover ";"

2021-08-11 00:39 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/TableBody/index.jsx
> +                        </TableRow>
alterado

2021-08-11 00:40 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +import TableMarket from '../components/TableMarket';
retirado

2021-08-11 00:40 UTC, jesus91fael commented on projects/crypto-currency/destemidos/App/src/pages/Markets.jsx
> +      setloading(true);
retirado

2021-08-11 12:11 UTC, mattheuzz approved these changes

2021-08-11 12:57 UTC, lucasbarbosadias approved these changes

2021-08-11 20:21 UTC, merged