New route wallet
paketaacademy/class2 pull request #141
Opened 2021-08-10 20:54 UTC by renatosheep

criação da rota para compra

2021-08-10 20:56 UTC, Leringit approved these changes
revisado e ok

2021-08-10 21:00 UTC, talesperes requested changes

2021-08-10 21:00 UTC, talesperes commented on projects/crypto-currency/iluminados/api/src/routes/modules/wallets-sell.js
> +    }
Faz sentido esse `if` vazio?

2021-08-10 21:04 UTC, renatosheep commented on projects/crypto-currency/iluminados/api/src/routes/modules/wallets-sell.js
> +    }
Tales, esse arquivo wallets-seel.js ainda não ficou pronto. Eu subi ele porque foram juntos outros arquivos

2021-08-10 21:06 UTC, talesperes commented on projects/crypto-currency/iluminados/api/src/routes/modules/wallets-sell.js
> +    }
ok

2021-08-11 18:52 UTC, alissonperim approved these changes

2021-08-12 11:59 UTC, merged