feature: criada rota login
paketaacademy/class2 pull request #190
Opened 2021-08-17 20:24 UTC by jesus91fael

2021-08-17 20:41 UTC, lucasbarbosadias requested changes

2021-08-17 20:41 UTC, lucasbarbosadias commented on projects/generic-trello/superman/app/src/App.js
> +            {/* <Menu /> */}
Isso era para estar comentado mesmo?

2021-08-17 20:41 UTC, lucasbarbosadias commented on projects/generic-trello/superman/app/src/components/ContentPage/index.jsx
> +      </Route> */}
Isso era para estar comentado mesmo?

2021-08-18 00:39 UTC, jesus91fael commented on projects/generic-trello/superman/app/src/App.js
> +            {/* <Menu /> */}
retirado comentário

2021-08-18 00:39 UTC, jesus91fael commented on projects/generic-trello/superman/app/src/components/ContentPage/index.jsx
> +      </Route> */}
retirado comentário

2021-08-18 01:33 UTC, lucasbarbosadias approved these changes

2021-08-18 11:12 UTC, Leringit approved these changes
revisado - ok

2021-08-18 11:12 UTC, merged