feture: cria rota de get all para o board
paketaacademy/class2 pull request #194
Opened 2021-08-18 13:37 UTC by alissonperim

2021-08-18 13:39 UTC, renatosheep approved these changes

2021-08-18 13:40 UTC, carolinespezzatto approved these changes

2021-08-18 14:07 UTC, Tautorn requested changes

2021-08-18 14:07 UTC, Tautorn commented on projects/generic-trello/batman/api/src/controllers/Boards/get.js
> +      await boards.find({}).exec(boards.find({ user: userId }))
Por que executar um fullscan na tabela e depois passar um find com o usuário?

2021-08-18 14:07 UTC, Tautorn commented on projects/generic-trello/batman/api/src/controllers/Boards/get.js
> +        .send({ menssagem: `Erro ao tentar encontrar os boards - ${error}` })
Renomear para `message`. Não utlize palavras em português para os retornos.

2021-08-18 14:08 UTC, Tautorn commented
Onde está a descrição do Pull Request?

2021-08-18 17:59 UTC, alissonperim commented
rsrs, eu pensei que o título desse PR já serveria como descrição, porque é só isso que ele faz mesmo ^^ foi mal... Vou fazer as modificações e enviar novamente

2021-08-19 17:34 UTC, Tautorn requested changes

2021-08-19 17:34 UTC, Tautorn commented on projects/generic-trello/batman/api/src/controllers/Boards/get.js
> +        return res
Aqui na verdade é só 404. Vai buscar os boards e não vai ter para aquele user.

2021-08-19 17:34 UTC, Tautorn commented on projects/generic-trello/batman/api/src/controllers/Boards/get.js
> +          .send({ message: `Usuário não está registrado em nenhum board registrado!` })
`O usuário não possui boards vinculados`

2021-08-19 17:47 UTC, alissonperim commented on projects/generic-trello/batman/api/src/controllers/Boards/get.js
> +        return res
Corrigido para status 404

2021-08-19 17:47 UTC, alissonperim commented on projects/generic-trello/batman/api/src/controllers/Boards/get.js
> +          .send({ message: `Usuário não está registrado em nenhum board registrado!` })
Corrigido message

2021-08-19 18:57 UTC, renatosheep approved these changes

2021-08-19 18:58 UTC, carolinespezzatto approved these changes

2021-08-19 18:59 UTC, carolinespezzatto approved these changes

2021-08-19 18:59 UTC, renatosheep approved these changes

2021-08-23 13:54 UTC, Tautorn approved these changes

2021-08-23 13:54 UTC, merged