Feature/creating-board
paketaacademy/class2 pull request #203
Opened 2021-08-18 20:52 UTC by lucasbarbosadias

Criando os bords pela rota POST e alterando o nome dos arquivos que fazem validação com o YUP.

2021-08-18 20:53 UTC, jesus91fael approved these changes

2021-08-18 21:17 UTC, Leringit approved these changes
revisado - ok
validações yup - ok

2021-08-19 12:08 UTC, Tautorn requested changes

2021-08-19 12:08 UTC, Tautorn commented on projects/generic-trello/superman/api/routes/board.js
> +  const boardData = req.body
Que tal assim?
```suggestion
  const { title, description, idUser, members } = req.body
  
  const board = new Boards({ title, description, idUser, members })
```

2021-08-19 12:08 UTC, Tautorn commented on projects/generic-trello/superman/api/routes/register.js
> +import { userSchema } from './configs/yupValidation.js'
deve chamar apenas de validation. Yup é só a ferramenta que está sendo utilizada

2021-08-19 12:08 UTC, Tautorn commented on projects/generic-trello/superman/api/routes/register.js
> +      return res.status(409).send({ msg: 'E-mail já cadastrado!' })
Não deve ser criado abreviaturas. Chame de `message`

2021-08-19 12:08 UTC, Tautorn commented on projects/generic-trello/superman/api/routes/register.js
> +      res.status(201).send({ msg: 'Cadastro realizado com sucesso!' })
Não deve ser criado abreviaturas. Chame de message

2021-08-19 13:40 UTC, lucasbarbosadias commented on projects/generic-trello/superman/api/routes/board.js
> +  const boardData = req.body
Muito melhor assim, obrigado!

2021-08-23 15:23 UTC, Tautorn approved these changes

2021-08-23 15:23 UTC, Tautorn requested changes

2021-08-23 15:23 UTC, Tautorn commented on projects/generic-trello/superman/api/routes/board.js
> +    const board = new Boards({ title, description, idUser, members })
Não deve ser idUser, apenas `user`

2021-08-23 17:30 UTC, merged