Menu
paketaacademy/class2 pull request #229
Opened 2021-08-20 19:31 UTC by LarissaNunesSilva

2021-08-20 19:31 UTC, jesus91fael approved these changes

2021-08-20 21:01 UTC, lucasbarbosadias requested changes

2021-08-20 21:01 UTC, lucasbarbosadias commented on projects/generic-trello/superman/app/src/components/Menu/index.jsx
> +    console.log(user,'oi')
Remover console.log

2021-08-23 12:29 UTC, lucasbarbosadias approved these changes

2021-08-23 12:29 UTC, merged