Feature/create market page
paketaacademy/class2 pull request #96
Opened 2021-07-30 03:35 UTC by cogumos

Created initial configurations of market page.

2021-07-30 11:53 UTC, Tautorn requested changes

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Body/index.jsx
> +            <Route path="/Markets">
utilizar rotas em lowercase e em português

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +
Qual a finalidade dessa quebra de linhas?

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +import { useStyles } from './styles';
o que é o useStyles?

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +function createData(name, calories, fat, carbs, protein) {
Qual a finalidade dessa função? Ela recebe os valores e retorna eles mesmo em um objeto

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +function descendingComparator(a, b, orderBy) {
criar um arquivo de utilitário `utils.js` e adicionar essa funções dentro

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +function getComparator(order, orderBy) {
`utils.js`

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +function stableSort(array, comparator) {
`utils.js`

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +function EnhancedTableHead(props) {
O nome não é sugestivo. É o componente principal? Então ele deve conter o mesmo nome do arquivo

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +                {headCells.map((headCell) => (
Corrigir identação e adicionar uma função para resolver a renderização do map. Não deve ser feito diretamente nele

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +    const [order, setOrder] = React.useState('asc');
import { useState } from 'react'.

Não utilize React.${any}, sempre faça a importação no inicio.

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +        if (selectedIndex === -1) {
Qual a necessidade dessas condições?

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +                                <TableRow style={{ height: (53) * emptyRows }}>
Não utilizar stlye inline

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +                                            <TableCell component="th" id={labelId} scope="row" padding="none">
Por que utilizar id?

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +                                            onClick={(event) => handleClick(event, row.name)}
Por que passar o nome e não id?

2021-07-30 11:53 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/styles.jsx
> +const useStyles = makeStyles((theme) => ({
Não deve ser utilizado makeStyles do CSS, sobrescrevea os elementos diretamete no themeprovider ou no styled components com `&&`

2021-07-30 12:49 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/Body/index.jsx
> +            <Route path="/Markets">
Ah, certo! Consertarei agora mesmo as rotas, mas imaginei que tivesse que ser em inglês. Irei alterar para português e tudo lowercase.

2021-07-30 12:49 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +
Irei excluir todas, fiz isso apenas para separar e acabei commitando sem tirar os espaços, visto que vou dar continuidade agora. Porque fiz apenas a base da tabela ontem, estou estudando e montando a tabela.

2021-07-30 12:49 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +import { useStyles } from './styles';
é o nome que dei com base no material-UI que estou usando como referência (e foi assim que foi utilizado como estilização lá), mas irei alterar visto que ele não é um hook. A página não está pronta, começarei a fazer toda certinha hoje de fato, visto que passei o dia estudando sobre a tabela e realmente só fiz o escopo dela (parei em um momento porque precisava dormir, mas darei continuidade agora).

2021-07-30 12:49 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +function createData(name, calories, fat, carbs, protein) {
Peguei como base para aprender a fazer a tabela, ainda estou modificando, visto que estou aprendendo e botando em prática a tabela. Muitos elementos irei remover e ver quais serão necessários ou não.

2021-07-30 12:49 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +function descendingComparator(a, b, orderBy) {
Irei criar!

2021-07-30 12:50 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +        if (selectedIndex === -1) {
Commitei dessa forma para verem o processo que eu estava fazendo, mas foi so pra fazer a base da tabela. Estou removendo muita coisa, mudando e adicionando conforme vou entendendo melhor para que fique da forma que quero e precisa ficar. Logo mais será atualizado no próximo commit que eu der. Realmente usei como base um exemplo um pouco mais complicado do material-UI, então ainda estou estudando ele.

2021-07-30 12:50 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +                                <TableRow style={{ height: (53) * emptyRows }}>
Já irei separar tudo.

2021-07-30 12:50 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +                                            onClick={(event) => handleClick(event, row.name)}
Fiz so a base mesmo da tabela, aonde irei modificar totalmente o código para melhor entendimento e otimização. Commitei dessa forma para verem o processo que eu estava fazendo, mas foi so pra fazer a base da tabela. Estou removendo muita coisa, mudando e adicionando conforme vou entendendo melhor para que fique da forma que quero e precisa ficar.

2021-07-30 12:50 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/styles.jsx
> +const useStyles = makeStyles((theme) => ({
Certo! Como mencionei antes, peguei como base um código de tabela do material-UI e estou mofiicando aos poucos todo o codigo.

2021-07-30 12:52 UTC, cogumos commented on projects/crypto-currency/destemidos/App/src/components/TableMarket/index.jsx
> +                                            <TableCell component="th" id={labelId} scope="row" padding="none">
Foi como vi no exemplo em que estou usando como referência. Ainda estou estudando melhor o código e irei otimizar e deixar da forma mais clara e enxuta possível. Realmente, só fiz uma base ai da forma que vi no exemplo do material-UI.

2021-08-02 11:56 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/components/Body/index.jsx
> +            <Route path="/Markets">
Inglês só questão de código mesmo, com relação as rotas pode deixar em português que é o nome que vai aparecer na navegação para o usuário

2021-08-02 17:49 UTC, mattheuzz approved these changes

2021-08-03 18:16 UTC, jesus91fael approved these changes

2021-08-03 18:20 UTC, merged