Feature/integration form
paketaacademy/class2 pull request #97
Opened 2021-07-30 15:00 UTC by lucasbarbosadias

2021-07-30 16:12 UTC, jesus91fael approved these changes

2021-07-30 16:15 UTC, mattheuzz approved these changes

2021-07-30 17:23 UTC, jesus91fael approved these changes

2021-07-30 17:24 UTC, jesus91fael approved these changes

2021-07-30 17:37 UTC, Tautorn requested changes

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/routes/market.js
> +import { config } from './configs_export/config.js'
não precisa chamar de export só porque tem exportações dentro.

A pasta principal é a configs e dentro dela os arquivos como configurações de serviço...

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +  const carteira = req.body.carteira
o que é carteira?

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +    res.send(savedUser)
retornar status 201 quando algo foi criado.

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +import React, { useState } from 'react';
';'

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +  function handleInputChange(event){
Dê preferência para arrow function ao invés de function

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +        <form className={classes.form} onSubmit={handleFormSubmit} noValidate>
`handleSubmit`

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +                onChange={handleInputChange}
`handleChange` ou `handlePasswordChange`

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
>    const classes = useStyles();
Não utilizar useStyles, mudar para styled-components ou settar a classe diretamente na tag

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +      axios.post('http://localhost:3000/singin', inputs).then(response => {
Buscar por variável https://create-react-app.dev/docs/adding-custom-environment-variables/

2021-07-30 17:37 UTC, Tautorn commented on projects/crypto-currency/destemidos/App/src/pages/SignUp/index.js
> +      alert('Cadastro realizado com sucesso!');
Não utilize alert, informe o usuário atráves de um toaster.
https://material-ui.com/pt/components/snackbars/

2021-07-30 19:26 UTC, lucasbarbosadias commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +  const carteira = req.body.carteira
Carteira só foi um exemplo, onde estávamos testando se era possível inserir um objeto dentro da collection, ai como deu certo deixamos apenas para ter uma ideia de como iria ficar quando iniciarmos a parte do perfil do usuário, pensamos em deixar uma "carteira" que todas as compras das criptomoedas vão ai dentro, embora seja em outro arquivo está ai pra vermos como vai ficar, ai depois só removemos dai e colocamos no correto.

2021-08-02 11:55 UTC, Tautorn commented on projects/crypto-currency/destemidos/Api/routes/singin.js
> +  const carteira = req.body.carteira
Wallet (carteira) precisa ser uma outra collection onde uma das chaves do documento é `user` (que é o ID da collection user)

2021-08-02 14:15 UTC, jesus91fael approved these changes

2021-08-02 14:26 UTC, mattheuzz approved these changes

2021-08-03 18:21 UTC, merged