feature: dataBase
paketaacademy/class2 pull request #98
Opened 2021-07-30 17:07 UTC by renatosheep

Funcionalidades realizadas entre o Banco de Dados e a API

2021-07-30 17:40 UTC, Tautorn requested changes

2021-07-30 17:40 UTC, Tautorn commented on projects/crypto-currency/iluminados/api/src/routes/modules/coinOfTheDay.js
> +import { configuration } from './configs/config.js'
Nome repetitivo.
configs/lunarCrushApi.js

2021-07-30 17:40 UTC, Tautorn commented on projects/crypto-currency/iluminados/api/src/routes/modules/coinOfTheDay.js
>          res.json(resp)
Adicionar o status da resposta

https://expressjs.com/pt-br/api.html#res.status

2021-07-30 17:40 UTC, Tautorn commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/dataBase.js
> +// userSchema.pre('save', async (next) =>{
remover comentários

2021-07-30 17:40 UTC, Tautorn commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/dataBase.js
> +// import bcrypt from "bcryptjs"
remover comentário

2021-07-30 17:40 UTC, Tautorn commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/dataBase.js
> +mongoose.connect('mongodb+srv://Iluminados:VfJmqXxKvxHdqqBk@cluster0.ytefl.mongodb.net/myFirstDatabase?retryWrites=true&w=majority', params);
utilizar variável de ambiente `.env` para informar o uri

2021-07-30 17:40 UTC, Tautorn commented on projects/crypto-currency/iluminados/api/src/routes/modules/register.js
> +      res.send(savedUser);
https://expressjs.com/pt-br/api.html#res.status

2021-07-30 18:26 UTC, renatosheep commented on projects/crypto-currency/iluminados/api/src/routes/modules/coinOfTheDay.js
> +import { configuration } from './configs/config.js'
Corrigido

2021-07-30 18:26 UTC, renatosheep commented on projects/crypto-currency/iluminados/api/src/routes/modules/coinOfTheDay.js
>          res.json(resp)
Corrigido

2021-07-30 18:26 UTC, renatosheep commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/dataBase.js
> +// userSchema.pre('save', async (next) =>{
Corrigido

2021-07-30 18:28 UTC, renatosheep commented on projects/crypto-currency/iluminados/api/src/routes/modules/register.js
> +      res.send(savedUser);
Corrigido

2021-07-30 18:57 UTC, renatosheep commented on projects/crypto-currency/iluminados/api/src/routes/modules/configs/dataBase.js
> +mongoose.connect('mongodb+srv://Iluminados:VfJmqXxKvxHdqqBk@cluster0.ytefl.mongodb.net/myFirstDatabase?retryWrites=true&w=majority', params);
Tentei realizar a alteração, porém não funcionou.
Estou deixando como está

2021-08-02 11:54 UTC, Tautorn approved these changes

2021-08-02 11:54 UTC, Tautorn commented
conflitos

2021-08-02 12:04 UTC, renatosheep reviewed
Corrigido

2021-08-02 14:00 UTC, merged